output:
  output_dir: 'data//'
  model_reporters: 
    av_charge: 'av_charge'
    completed_trip: 'completed_trip'
    dead_cars: 'dead_cars'
    charge_load: 'charge_load'
    date_time: 'date_time'
    av_moving: 'av_moving'
    av_home: 'av_home'
    av_work: 'av_work'
    av_random: 'av_random'
  agent_reporters: 
    charge: "charge"
    last_location: 'last_location'
    next_location: 'next_location'
    pos: 'pos'
    charging: 'charging'
    wait: 'wait'
    moving: 'moving'
    completed_trip: 'completed_trip'
    dist_moved: 'dist_moved'

model_params: 
  start_date : '2022-01-01'
  width: 5.
  height: 5.
  model_name :  0
  tol: 0.01
  POI_file: 'inputs/POIs.csv'
  time_increment: 1 # hours
  price: 0
  location_probs: 'inputs/location_probs.csv'

agent_params: 
  EVs: 
    Type: 'EV'
    from_file: False
    num_agents: 1000
    # file: 'inputs/'
    discharge_rate: 0.2
    MoveType :  'loc'
    charging: False
    max_range: 1
    speed: 2
    home_stay: 10
    work_stay: 8
    rand_stay: 3
    completed_trip: 0
    dist_moved: 0
    max_work_d: 3
    home_charge_rate: 0.05
    work_charge_rate: 0.05
    ChargePoint_charge_rate: 0.2
  Grid_Points:
    Type: 'GP'
    grid_spacing :  20
    cars_passing: 0
  Charge_Points:
    Type: 'CP'
    CP_loc: 'random'
    CP_capacity: 10
    N_Charge: 10
    charge_rate :  0.2
    cars_charging: 0
    full: False


