model_params: 
  POI_file: 'inputs/Point Edward_poi_data.csv'
  Traffic_file: 'None'

agent_params: 
  EVs: 
    num_agents: 100
  Charge_Points:
    CP_loc: 'inputs/Point Edward_charging_stations.csv'
